// Generated by Wrangler by running `wrangler types`

interface Env {
	VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
	DB_URL: string;
	SESSION_SECRET: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	API_GATEWAY_URL: string;
	API_GATEWAY_KEY: string;
	DB: D1Database;
}
